const ProductsList = [
    {
        id: 0,
        category: 'Caps',
        itemList: [
            {
                id: 0,
                parentID:0,
                pImg: require('../assets/images/products/caps/cap1.webp'),
                pTitle: "cap 081",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['red', 'green', 'blue'],
                pPrice: 10,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 1,
                parentID:0,
                pImg: require('../assets/images/products/caps/cap2.webp'),
                pTitle: "cap 965",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 11,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
        ]
    },
    {
        id: 1,
        category: 'Jeans',
        itemList: [
            {
                id: 0,
                parentID:1,
                pImg: require('../assets/images/products/jeans/jeans1.webp'),
                pTitle: "jeans 876",
                pSize: ['30', '31', '32', '33', '34'],
                pColor: ['blue', 'light blue', 'black'],
                pPrice: 15,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 1,
                parentID:1,
                pImg: require('../assets/images/products/jeans/jeans2.webp'),
                pTitle: "jeans 324",
                pSize: ['30', '31', '32', '33', '34'],
                pColor: ['blue', 'gray', 'black'],
                pPrice: 10,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
            {
                id: 2,
                parentID:1,
                pImg: require('../assets/images/products/jeans/jeans3.webp'),
                pTitle: "jeans 009",
                pSize: ['30', '31', '32', '33', '34'],
                pColor: ['black', 'blue', 'gray'],
                pPrice: 25,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 3,
                parentID:1,
                pImg: require('../assets/images/products/jeans/jeans4.webp'),
                pTitle: "jeans 126",
                pSize: ['30', '31', '32', '33', '34'],
                pColor: ['gray', 'white', 'navy blue'],
                pPrice: 30,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
            {
                id: 4,
                parentID:1,
                pImg: require('../assets/images/products/jeans/jeans5.webp'),
                pTitle: "jeans 367",
                pSize: ['30', '31', '32', '33', '34'],
                pColor: ['black', 'blue', 'gray'],
                pPrice: 17,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 5,
                parentID:1,
                pImg: require('../assets/images/products/jeans/jeans6.webp'),
                pTitle: "jeans 289",
                pSize: ['30', '31', '32', '33', '34'],
                pColor: ['green', 'blue', 'light gray'],
                pPrice: 20,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
        ]
    },
    {
        id: 2,
        category: 'Polo',
        itemList: [
            {
                id: 0,
                parentID:2,
                pImg: require('../assets/images/products/polo/polo1.webp'),
                pTitle: "polo 445",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['red', 'green', 'blue'],
                pPrice: 10,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 1,
                parentID:2,
                pImg: require('../assets/images/products/polo/polo2.webp'),
                pTitle: "polo 347",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 11,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
            {
                id: 2,
                parentID:2,
                pImg: require('../assets/images/products/polo/polo3.webp'),
                pTitle: "polo 890",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 12,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 3,
                parentID:2,
                pImg: require('../assets/images/products/polo/polo4.webp'),
                pTitle: "polo 234",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 13,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
            {
                id: 4,
                parentID:2,
                pImg: require('../assets/images/products/polo/polo5.webp'),
                pTitle: "polo 148",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 14,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 5,
                parentID:2,
                pImg: require('../assets/images/products/polo/polo6.webp'),
                pTitle: "polo 008",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 15,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
            {
                id: 6,
                parentID:2,
                pImg: require('../assets/images/products/polo/polo7.webp'),
                pTitle: "polo 390",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 16,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
        ]
    },
    {
        id: 3,
        category: 'Shirts',
        itemList: [
            {
                id: 0,
                parentID:3,
                pImg: require('../assets/images/products/shirts/shirts1.webp'),
                pTitle: "shirt 223",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['red', 'green', 'blue'],
                pPrice: 10,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 1,
                parentID:3,
                pImg: require('../assets/images/products/shirts/shirts2.webp'),
                pTitle: "shirt 567",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 8,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
            {
                id: 2,
                parentID:3,
                pImg: require('../assets/images/products/shirts/shirts3.webp'),
                pTitle: "shirt 005",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 11,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 3,
                parentID:3,
                pImg: require('../assets/images/products/shirts/shirts4.webp'),
                pTitle: "shirt 324",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 12,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
            {
                id: 4,
                parentID:3,
                pImg: require('../assets/images/products/shirts/shirts5.webp'),
                pTitle: "shirt 340",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 13,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 5,
                parentID:3,
                pImg: require('../assets/images/products/shirts/shirts6.webp'),
                pTitle: "shirt 113",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 14,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
        ]
    },
    {
        id: 4,
        category: 'Shoes',
        itemList: [
            {
                id: 0,
                parentID:4,
                pImg: require('../assets/images/products/shoes/shoes1.webp'),
                pTitle: "shoes 223",
                pSize: ['8', '9', '11', '12'],
                pColor: ['black', 'brown', 'gray'],
                pPrice: 10,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 1,
                parentID:4,
                pImg: require('../assets/images/products/shoes/shoes2.webp'),
                pTitle: "shoes 567",
                pSize: ['8', '9', '11', '12'],
                pColor: ['black', 'brown', 'gray'],
                pPrice: 11,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
            {
                id: 2,
                parentID:4,
                pImg: require('../assets/images/products/shoes/shoes3.webp'),
                pTitle: "shoes 123",
                pSize: ['8', '9', '11', '12'],
                pColor: ['black', 'brown', 'gray'],
                pPrice: 15,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 3,
                parentID:4,
                pImg: require('../assets/images/products/shoes/shoes4.webp'),
                pTitle: "shoes 008",
                pSize: ['8', '9', '11', '12'],
                pColor: ['black', 'brown', 'gray'],
                pPrice: 20,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
            {
                id: 4,
                parentID:4,
                pImg: require('../assets/images/products/shoes/shoes5.webp'),
                pTitle: "shoes 456",
                pSize: ['8', '9', '11', '12'],
                pColor: ['black', 'brown', 'gray'],
                pPrice: 23,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 5,
                parentID:4,
                pImg: require('../assets/images/products/shoes/shoes6.webp'),
                pTitle: "shoes 789",
                pSize: ['8', '9', '11', '12'],
                pColor: ['black', 'brown', 'gray'],
                pPrice: 19,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
        ]
    },
    {
        id: 5,
        category: 'Shorts',
        itemList: [
            {
                id: 0,
                parentID:5,
                pImg: require('../assets/images/products/shorts/short1.webp'),
                pTitle: "shorts 081",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['red', 'green', 'blue'],
                pPrice: 10,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 1,
                parentID:5,
                pImg: require('../assets/images/products/shorts/short2.webp'),
                pTitle: "shorts 965",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 11,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
            {
                id: 2,
                parentID:5,
                pImg: require('../assets/images/products/shorts/short3.webp'),
                pTitle: "shorts 445",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 12,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 3,
                parentID:5,
                pImg: require('../assets/images/products/shorts/short4.webp'),
                pTitle: "shorts 223",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 13,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
        ]
    },
    {
        id: 6,
        category: 'Trousers',
        itemList: [
            {
                id: 0,
                parentID:6,
                pImg: require('../assets/images/products/trousers/trouser1.webp'),
                pTitle: "trouser 554",
                pSize: ['30', '31', '32', '33', '34'],
                pColor: ['red', 'green', 'blue'],
                pPrice: 14,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 1,
                parentID:6,
                pImg: require('../assets/images/products/trousers/trouser2.webp'),
                pTitle: "trouser 223",
                pSize: ['30', '31', '32', '33', '34'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 15,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
            {
                id: 2,
                parentID:6,
                pImg: require('../assets/images/products/trousers/trouser3.webp'),
                pTitle: "trouser 228",
                pSize: ['30', '31', '32', '33', '34'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 16,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 3,
                parentID:6,
                pImg: require('../assets/images/products/trousers/trouser4.webp'),
                pTitle: "trouser 998",
                pSize: ['30', '31', '32', '33', '34'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 17,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
            {
                id: 4,
                parentID:6,
                pImg: require('../assets/images/products/trousers/trouser5.webp'),
                pTitle: "trouser 334",
                pSize: ['30', '31', '32', '33', '34'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 18,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
        ]
    },
    {
        id: 7,
        category: 'Tshirt',
        itemList: [
            {
                id: 0,
                parentID:7,
                pImg: require('../assets/images/products/tshirt/tshirt1.webp'),
                pTitle: "tshirt 667",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['red', 'green', 'blue'],
                pPrice: 19,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 1,
                parentID:7,
                pImg: require('../assets/images/products/tshirt/tshirt2.webp'),
                pTitle: "tshirt 223",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 20,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
            {
                id: 2,
                parentID:7,
                pImg: require('../assets/images/products/tshirt/tshirt3.webp'),
                pTitle: "tshirt 667",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['red', 'green', 'blue'],
                pPrice: 21,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 3,
                parentID:7,
                pImg: require('../assets/images/products/tshirt/tshirt4.webp'),
                pTitle: "tshirt 889",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 22,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
            {
                id: 4,
                parentID:7,
                pImg: require('../assets/images/products/tshirt/tshirt5.webp'),
                pTitle: "tshirt 267",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['red', 'green', 'blue'],
                pPrice: 23,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
            {
                id: 5,
                parentID:7,
                pImg: require('../assets/images/products/tshirt/tshirt6.webp'),
                pTitle: "tshirt 998",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['yellow', 'purple', 'white'],
                pPrice: 24,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'normal',
            },
            {
                id: 6,
                parentID:7,
                pImg: require('../assets/images/products/tshirt/tshirt7.webp'),
                pTitle: "tshirt 290",
                pSize: ['S', 'M', 'L', 'XL'],
                pColor: ['red', 'green', 'blue'],
                pPrice: 25,
                pDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                pType: 'future',
            },
        ]
    },
];


export default ProductsList;